# Generated by Django 5.1.3 on 2024-11-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "Movies"},
        ),
    ]
